<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.ML" Version="5.0.0" />
    <PackageReference Include="MQTTnet" Version="5.2.0.1603" />
    <PackageReference Include="Microsoft.Extensions.ML" Version="5.0.0" />
  
    
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\prediction.client\prediction.client.esproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
    <ProjectReference Include="..\prediction.ServiceDefaults\prediction.ServiceDefaults.csproj" />
  </ItemGroup>
  <ItemGroup Label="PredictionModel">
    <None Include="PredictionModel.mlnet">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>